name: Dump firmware

on:
  workflow_dispatch:
    inputs:
      ota:
        description: 'OTA'
        required: true

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install git libguestfs-tools
        curl -L https://github.com/rajkale99/atools/archive/refs/tags/initial.tar.gz -o - |tar xzf -
        sudo bash setup.sh > /dev/null
        
    - name: Download
      id: download
      run: |
        curl -L ${{ inputs.ota }} -o ota.zip
        echo ::set-output name=ota_ver::`unzip -p ota.zip META-INF/com/android/metadata | grep ^version_name= | cut -b 14-`

    - name: Dump
      run: |
        sudo bash tools/rom_extract.sh ota.zip
        
    - name: Mount 
      run: |
         cd dumps/ota 
         sudo mkdir system system_ext product odm vendor
         guestmount -a system.img -i system 
         ls system
         guestmount -a system_ext.img -i system_ext 
         ls system_ext
         guestmount -a odm.img -i odm
         ls odm
         guestmount -a vendor.img -i vendor
         ls vendor
         guestmount -a odm.img -i odm 
         ls odm
         
    - name: Zip
      run: |
        cd dumps/ota && sudo bash ../../zip.sh
      
    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: dumps/ota/*.zip
        artifactErrorsFailBuild: true
        body: ${{ inputs.ota }}
        tag: ${{ steps.download.outputs.ota_ver }}
        token: ${{ secrets.GITHUB_TOKEN }}
