name: Dump firmware

on:
  workflow_dispatch:
    inputs:
      ota:
        description: 'OTA'
        required: true

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: |
        sudo apt update
        pwd
        ls
        sudo apt -y install git libguestfs-tools gcc libfuse-dev erofs-utils aria2 arj brotli cabextract cmake device-tree-compiler gcc g++ git liblz4-tool liblzma-dev libtinyxml2-dev lz4 mpack openjdk-11-jdk p7zip-full p7zip-rar python3 python3-pip rar sharutils unace unrar unzip uudeview xz-utils zip zlib1g-dev python3-protobuf build-essential libssl-dev libffi-dev python3-dev > /dev/null

  download:
   runs-on: ubuntu-latest
   needs: dump
   steps:
   - name: Download
     id: download
     run: |
        curl -L ${{ inputs.ota }} -o ota.zip
        echo ::set-output name=ota_ver::`unzip -p ota.zip META-INF/com/android/metadata | grep ^version_name= | cut -b 14-`
        pwd
        ls

  Extract:
   runs-on: ubuntu-latest
   needs: [dump, download]
   steps:
   - name: Checkout repo
     uses: actions/checkout@v4

   - name: Extract
     run: |
        pwd
        ls
        sudo bash tools/rom_extract.sh ../../ota.zip
        
  Mount:
   runs-on: ubuntu-latest
   needs: [dump, download, Extract]
   steps:        
   - name: dump erofs
     run: |
         cd atools/dumps/ota 
         sudo mkdir system system_ext product odm vendor
         dump.erofs system.img system/
         ls system
         dump.erofs system_ext.img system_ext/
         ls system_ext
         dump.erofs odm.img odm/
         ls odm
         dump.erofs vendor.img vendor/
         ls vendor
         dump.erofs product.img product/
         ls product
         
   - name: Zip
     run: |
        cd atools/dumps/ota && sudo bash ../../zip.sh
      
   - name: Upload release assets
     uses: ncipollo/release-action@v1
     with:
        artifacts: dumps/ota/*.zip
        artifactErrorsFailBuild: true
        body: ${{ inputs.ota }}
        tag: ${{ steps.download.outputs.ota_ver }}
        token: ${{ secrets.GITHUB_TOKEN }}
